[package]
name = "day-8-2020"
version = "0.1.0"
authors = ["Helio Chissini de Castro <helio@kde.org>"]
edition = "2018"

[dependencies]
clap = "2"
regex = "1"
advent_lib = { path = "../../advent-lib" }
