[workspace]
    members = [
        "advent-2019/day-1",
        "advent-2019/day-2",
        "advent-2019/day-3",
        "advent-2020/day-1",
        "advent-2020/day-2",
        "advent-2020/day-3",
        "advent-2020/day-4",
    ]