[workspace]
    members = [
        "2019/day-1",
        "2019/day-2",
        "2019/day-3",
        "2020/day-1",
        "2020/day-2",
        "2020/day-3",
        "2020/day-4",
        "2020/day-5",
    ]